version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    container_name: siconv_elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 1s
      timeout: 30s
      retries: 30
    ports:
      - "9200:9200"
    volumes:
      - ./sample/elasticsearch:/usr/share/elasticsearch/data

  postgres:
    image: postgres:9.5
    container_name: siconv_postgres
    environment:
      POSTGRES_DB: siconv
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./sample/postgres:/var/lib/postgresql/data

  siconv:
    build: .
    image: insighted4/siconv
    environment:
      - SICONV_DATABASE_URL=postgres://postgres:secret@postgres:5432/siconv
      - SICONV_TOKEN=5vnzGE4sB11kWjXOWNDUB8WrxDCoRYL1kXslpgRACe8=
    depends_on:
      - elasticsearch
      - postgres
    ports:
      - "8080:8080"