version: "3"
services:
  postgres:
    image: postgres:9.5
    environment:
      POSTGRES_DB: siconv
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - ./sample/postgres:/var/lib/postgresql/data
