[[constraint]]
  name = "github.com/appleboy/gofight"
  version = "2.0.0"

[[constraint]]
  name = "github.com/gin-contrib/cors"
  version = "1.2.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"


[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/go-pg/pg"
  version = "6.11.2"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true






[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"
